site_name: DNS-SecLab
site_url: https://netexperiments.github.io/dnssecurity/

site_description: DNS-SecLab documents a hands-on study of DNS security, developed as part of a Master's dissertation at Instituto Superior Técnico (IST). It covers both defensive mechanisms that strengthen DNS integrity and privacy, as well as a broad range of attack techniques demonstrated in GNS3, a controlled lab environment.
site_author: Pedro Luís Barão

repo_url: https://github.com/netexperiments/dnssecurity
repo_name: netexperiments/dnssecurity

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.tabs  
    - navigation.indexes
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - toc:
      toc_depth: 0
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
#extra_css:
 # - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pedroluisbarao

nav:
  - Home: index.md
  - Lab Setup: setup.md
  - DNS Security and Privacy Enhancements:
    - enhancements/index.md
    - DNSSEC: enhancements/dnssec.md
    - DNS-over-HTTPS (DoH): enhancements/doh.md
  - DNS Attacks and Countermeasures:
    - attacks/index.md
    - DNS Protocol and Resolution Attacks:
      - attacks/protocol/index.md
      - DNS Rebinding: attacks/protocol/rebinding.md
      - DHCP DNS Spoofing: attacks/protocol/dhcp-dns-spoofing.md
    - DNS Server and Infrastructure Attacks:
      - attacks/server/index.md
      - NXDOMAIN DDoS: attacks/server/nxdomain-ddos.md
      - DNS Cache Poisoning: attacks/server/cache-poisoning.md
      - Kaminsky Cache Poisoning: attacks/server/kaminsky.md
      - Unauthorized Zone Transfer: attacks/server/zone-transfer.md
      - DNS ARP Poisoning: attacks/server/dns-arp-poisoning.md
    - DNS Abuse/Misuse Attacks:
      - attacks/abuse-misuse/index.md
      - DNS Amplification: attacks/abuse-misuse/amplification.md
      - DNS Fast Flux Single-based: attacks/abuse-misuse/ff-single.md
      - DNS Fast Flux Double-based: attacks/abuse-misuse/ff-double.md
      - DNS Tunneling: attacks/abuse-misuse/tunneling.md
      - DGA-based: attacks/abuse-misuse/dgas.md
      - Fast Flux and DGA-based Tunneling: attacks/abuse-misuse/ff-dgas-tunneling.md
